/* ==========================================================================
 *  Buka Delivery — lib/mock-data.ts
 *
 *  Προσωρινά δεδομένα μέχρι να συνδεθεί το Firebase.
 *  ΚΑΝΕΝΑ component δεν εισάγει απευθείας από εδώ — όλα περνούν από το
 *  `lib/data.ts`. Όταν μπει το Firestore, αυτό το αρχείο απλώς διαγράφεται.
 * ========================================================================== */

import type { Cuisine, Menu, Shop } from "@/types";

/* --------------------------------------------------------------------------
 *  Διευθύνσεις παράδοσης (μελλοντικά: users/{uid}/addresses)
 * -------------------------------------------------------------------------- */

export const DELIVERY_ADDRESSES: string[] = [
  "Κεντρική Πλατεία",
  "Οδός Ερμού 45",
  "Πανεπιστημιούπολη",
  "Παραλιακή Λεωφόρος 12",
];

/* --------------------------------------------------------------------------
 *  Κατηγορίες κουζίνας
 * -------------------------------------------------------------------------- */

export const CUISINES: Cuisine[] = [
  { id: "all", label: "Όλα", emoji: "🍽️" },
  { id: "souvlaki", label: "Σουβλάκι", emoji: "🥙" },
  { id: "pizza", label: "Πίτσα", emoji: "🍕" },
  { id: "burger", label: "Burger", emoji: "🍔" },
  { id: "coffee", label: "Καφές", emoji: "☕" },
  { id: "sweets", label: "Γλυκά", emoji: "🍰" },
  { id: "greek", label: "Μαγειρευτά", emoji: "🍲" },
  { id: "healthy", label: "Υγιεινά", emoji: "🥗" },
];

/* --------------------------------------------------------------------------
 *  Καταστήματα
 * -------------------------------------------------------------------------- */

export const SHOPS: Shop[] = [
  {
    id: "obelistirio-giannis",
    name: "Οβελιστήριο ο Γιάννης",
    cuisineLabel: "Σουβλάκι • Ψητά • Μεζέδες",
    cuisineIds: ["souvlaki", "greek"],
    rating: 4.8,
    reviews: 1240,
    etaMinutes: [25, 35],
    minOrder: 5,
    deliveryFee: 0,
    freeDeliveryOver: null,
    image:
      "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?auto=format&fit=crop&w=1000&q=80",
    gradient: "from-amber-200 to-orange-300",
    address: "Κεντρική Πλατεία 4",
    tag: { label: "Δωρεάν Delivery", tone: "green" },
  },
  {
    id: "pizza-roma",
    name: "Pizza Roma",
    cuisineLabel: "Πίτσα • Ιταλικά • Ζυμαρικά",
    cuisineIds: ["pizza"],
    rating: 4.6,
    reviews: 863,
    etaMinutes: [30, 40],
    minOrder: 8,
    deliveryFee: 1.5,
    freeDeliveryOver: 20,
    image:
      "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=1000&q=80",
    gradient: "from-red-200 to-orange-300",
    address: "Ερμού 45",
    tag: { label: "1+1 Δώρο", tone: "orange" },
  },
  {
    id: "burger-project",
    name: "The Burger Project",
    cuisineLabel: "Burger • Smash • Finger Food",
    cuisineIds: ["burger"],
    rating: 4.9,
    reviews: 2105,
    etaMinutes: [20, 30],
    minOrder: 7.5,
    deliveryFee: 1.2,
    freeDeliveryOver: 18,
    image:
      "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=1000&q=80",
    gradient: "from-yellow-200 to-amber-300",
    address: "Βενιζέλου 18",
    tag: { label: "Προσφορά -20%", tone: "orange" },
  },
  {
    id: "kafekopteio-ellas",
    name: "Καφεκοπτείο Ελλάς",
    cuisineLabel: "Καφές • Ροφήματα • Σνακ",
    cuisineIds: ["coffee", "sweets"],
    rating: 4.7,
    reviews: 517,
    etaMinutes: [15, 25],
    minOrder: 4,
    deliveryFee: 0,
    freeDeliveryOver: null,
    image:
      "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=1000&q=80",
    gradient: "from-stone-200 to-amber-200",
    address: "Πλατεία Δημαρχείου 2",
    tag: { label: "Δωρεάν Delivery", tone: "green" },
  },
  {
    id: "zacharoplasteio-melina",
    name: "Ζαχαροπλαστείο Μελίνα",
    cuisineLabel: "Γλυκά • Τούρτες • Σιροπιαστά",
    cuisineIds: ["sweets"],
    rating: 4.9,
    reviews: 944,
    etaMinutes: [35, 45],
    minOrder: 6,
    deliveryFee: 1.8,
    freeDeliveryOver: 25,
    image:
      "https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&w=1000&q=80",
    gradient: "from-pink-200 to-rose-300",
    address: "Αγίου Νικολάου 9",
    tag: { label: "Νέο στο Buka", tone: "purple" },
  },
  {
    id: "steki-tis-plateias",
    name: "Ταβέρνα το Στέκι της Πλατείας",
    cuisineLabel: "Μαγειρευτά • Παραδοσιακά",
    cuisineIds: ["greek", "healthy"],
    rating: 4.5,
    reviews: 388,
    etaMinutes: [40, 50],
    minOrder: 10,
    deliveryFee: 2,
    freeDeliveryOver: 30,
    image:
      "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1000&q=80",
    gradient: "from-emerald-200 to-teal-300",
    address: "Παλαιά Αγορά 31",
  },
];

/* --------------------------------------------------------------------------
 *  Μενού ανά κατάστημα
 *  Firestore: shops/{shopId}/menuCategories + shops/{shopId}/menuItems
 * -------------------------------------------------------------------------- */

export const MENUS: Record<string, Menu> = {
  /* ------------------------ Οβελιστήριο ο Γιάννης ------------------------ */
  "obelistirio-giannis": {
    shopId: "obelistirio-giannis",
    categories: [
      { id: "offers", label: "Προσφορές", emoji: "🔥", sortOrder: 1 },
      { id: "pita", label: "Πίτες", emoji: "🥙", sortOrder: 2 },
      { id: "merida", label: "Μερίδες", emoji: "🍖", sortOrder: 3 },
      { id: "sides", label: "Ορεκτικά", emoji: "🍟", sortOrder: 4 },
      { id: "drinks", label: "Ποτά", emoji: "🥤", sortOrder: 5 },
    ],
    items: [
      {
        id: "og-1",
        shopId: "obelistirio-giannis",
        categoryId: "offers",
        name: "Combo 2 Πίτες + Πατάτες + Αναψυκτικό",
        description:
          "Δύο πίτες της επιλογής σου, μερίδα πατάτες και αναψυκτικό 330ml.",
        price: 11.9,
        oldPrice: 14.5,
        popular: true,
        available: true,
        image:
          "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?auto=format&fit=crop&w=400&q=80",
      },
      {
        id: "og-2",
        shopId: "obelistirio-giannis",
        categoryId: "pita",
        name: "Πίτα Γύρος Χοιρινός",
        description: "Γύρος, τζατζίκι, ντομάτα, κρεμμύδι, πατάτες σε ζεστή πίτα.",
        price: 3.9,
        popular: true,
        available: true,
      },
      {
        id: "og-3",
        shopId: "obelistirio-giannis",
        categoryId: "pita",
        name: "Πίτα Κοτόπουλο",
        description: "Γύρος κοτόπουλο, σως γιαουρτιού, μαρούλι, ντομάτα.",
        price: 4.1,
        available: true,
      },
      {
        id: "og-4",
        shopId: "obelistirio-giannis",
        categoryId: "pita",
        name: "Πίτα Σουβλάκι Χοιρινό",
        description: "Καλαμάκι χοιρινό, τζατζίκι, ντομάτα, κρεμμύδι, πατάτες.",
        price: 3.7,
        available: true,
      },
      {
        id: "og-5",
        shopId: "obelistirio-giannis",
        categoryId: "merida",
        name: "Μερίδα Γύρος Χοιρινός",
        description: "400γρ. γύρος με πατάτες, πίτα, τζατζίκι και φρέσκια σαλάτα.",
        price: 10.5,
        popular: true,
        available: true,
      },
      {
        id: "og-6",
        shopId: "obelistirio-giannis",
        categoryId: "merida",
        name: "Μερίδα Παϊδάκια",
        description: "Χοιρινά παϊδάκια στα κάρβουνα με πατάτες και λεμόνι.",
        price: 13.9,
        available: true,
      },
      {
        id: "og-7",
        shopId: "obelistirio-giannis",
        categoryId: "sides",
        name: "Πατάτες Τηγανητές",
        description: "Φρέσκιες χειροποίητες πατάτες με ρίγανη.",
        price: 3.2,
        available: true,
      },
      {
        id: "og-8",
        shopId: "obelistirio-giannis",
        categoryId: "sides",
        name: "Τζατζίκι",
        description: "Παραδοσιακό τζατζίκι με στραγγιστό γιαούρτι.",
        price: 2.5,
        available: true,
      },
      {
        id: "og-9",
        shopId: "obelistirio-giannis",
        categoryId: "drinks",
        name: "Αναψυκτικό 330ml",
        description: "Cola, πορτοκαλάδα ή λεμονάδα.",
        price: 1.6,
        available: true,
      },
      {
        id: "og-10",
        shopId: "obelistirio-giannis",
        categoryId: "drinks",
        name: "Εμφιαλωμένο Νερό 500ml",
        description: "Φυσικό μεταλλικό νερό.",
        price: 0.6,
        available: true,
      },
    ],
  },

  /* ------------------------------ Pizza Roma ----------------------------- */
  "pizza-roma": {
    shopId: "pizza-roma",
    categories: [
      { id: "offers", label: "Προσφορές", emoji: "🔥", sortOrder: 1 },
      { id: "pizzas", label: "Πίτσες", emoji: "🍕", sortOrder: 2 },
      { id: "pasta", label: "Ζυμαρικά", emoji: "🍝", sortOrder: 3 },
      { id: "salads", label: "Σαλάτες", emoji: "🥗", sortOrder: 4 },
      { id: "drinks", label: "Ποτά", emoji: "🥤", sortOrder: 5 },
    ],
    items: [
      {
        id: "pr-1",
        shopId: "pizza-roma",
        categoryId: "offers",
        name: "1+1 Πίτσα Μεσαία",
        description:
          "Δύο μεσαίες πίτσες της επιλογής σου από τη βασική λίστα υλικών.",
        price: 15.9,
        oldPrice: 21.8,
        popular: true,
        available: true,
        image:
          "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=400&q=80",
      },
      {
        id: "pr-2",
        shopId: "pizza-roma",
        categoryId: "pizzas",
        name: "Margherita",
        description: "Σάλτσα ντομάτας, μοτσαρέλα, φρέσκος βασιλικός.",
        price: 8.5,
        available: true,
      },
      {
        id: "pr-3",
        shopId: "pizza-roma",
        categoryId: "pizzas",
        name: "Special Roma",
        description: "Ζαμπόν, μπέικον, πιπεριά, μανιτάρια, διπλή μοτσαρέλα.",
        price: 11.9,
        popular: true,
        available: true,
      },
      {
        id: "pr-4",
        shopId: "pizza-roma",
        categoryId: "pizzas",
        name: "Pepperoni Piccante",
        description: "Πεπερόνι, καυτερή πιπεριά, μοτσαρέλα, ρίγανη.",
        price: 11.2,
        available: true,
      },
      {
        id: "pr-5",
        shopId: "pizza-roma",
        categoryId: "pasta",
        name: "Καρμπονάρα",
        description: "Φρέσκια ταλιατέλα, κρέμα, μπέικον, παρμεζάνα.",
        price: 9.8,
        available: true,
      },
      {
        id: "pr-6",
        shopId: "pizza-roma",
        categoryId: "pasta",
        name: "Πέννες Αραμπιάτα",
        description: "Πικάντικη σάλτσα ντομάτας, σκόρδο, φρέσκος βασιλικός.",
        price: 8.4,
        available: true,
      },
      {
        id: "pr-7",
        shopId: "pizza-roma",
        categoryId: "salads",
        name: "Σαλάτα Καπρέζε",
        description: "Ντομάτα, μοτσαρέλα μπουφάλα, βασιλικός, ελαιόλαδο.",
        price: 7.9,
        available: true,
      },
      {
        id: "pr-8",
        shopId: "pizza-roma",
        categoryId: "drinks",
        name: "Αναψυκτικό 1,5L",
        description: "Οικογενειακή φιάλη.",
        price: 2.8,
        available: true,
      },
    ],
  },

  /* -------------------------- The Burger Project ------------------------- */
  "burger-project": {
    shopId: "burger-project",
    categories: [
      { id: "offers", label: "Προσφορές", emoji: "🔥", sortOrder: 1 },
      { id: "burgers", label: "Burgers", emoji: "🍔", sortOrder: 2 },
      { id: "sides", label: "Συνοδευτικά", emoji: "🍟", sortOrder: 3 },
      { id: "sauces", label: "Σως", emoji: "🥫", sortOrder: 4 },
      { id: "drinks", label: "Ποτά", emoji: "🥤", sortOrder: 5 },
    ],
    items: [
      {
        id: "bp-1",
        shopId: "burger-project",
        categoryId: "offers",
        name: "Double Smash Menu -20%",
        description:
          "Double smash burger, πατάτες τσένταρ και αναψυκτικό της επιλογής σου.",
        price: 12.8,
        oldPrice: 16,
        popular: true,
        available: true,
        image:
          "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=400&q=80",
      },
      {
        id: "bp-2",
        shopId: "burger-project",
        categoryId: "burgers",
        name: "Classic Smash",
        description:
          "Μοσχαρίσιο smash patty 120γρ., τσένταρ, πίκλες, κρεμμύδι, house sauce.",
        price: 8.9,
        popular: true,
        available: true,
      },
      {
        id: "bp-3",
        shopId: "burger-project",
        categoryId: "burgers",
        name: "Bacon Lover",
        description: "Διπλό patty, τραγανό μπέικον, τσένταρ, BBQ σως.",
        price: 11.5,
        available: true,
      },
      {
        id: "bp-4",
        shopId: "burger-project",
        categoryId: "burgers",
        name: "Crispy Chicken",
        description: "Τραγανό φιλέτο κοτόπουλο, coleslaw, μαγιονέζα λάιμ.",
        price: 9.6,
        available: true,
      },
      {
        id: "bp-5",
        shopId: "burger-project",
        categoryId: "burgers",
        name: "Garden Veggie",
        description: "Μπιφτέκι λαχανικών, αβοκάντο, ντομάτα, vegan μαγιονέζα.",
        price: 9.2,
        available: true,
      },
      {
        id: "bp-6",
        shopId: "burger-project",
        categoryId: "sides",
        name: "Πατάτες Cheddar & Bacon",
        description: "Τραγανές πατάτες με λιωμένη τσένταρ και μπέικον.",
        price: 5.4,
        available: true,
      },
      {
        id: "bp-7",
        shopId: "burger-project",
        categoryId: "sides",
        name: "Onion Rings",
        description: "8 τεμάχια, τραγανό πανάρισμα μπύρας.",
        price: 4.3,
        available: true,
      },
      {
        id: "bp-8",
        shopId: "burger-project",
        categoryId: "sauces",
        name: "House Sauce",
        description: "Η υπογραφή του μαγαζιού, 50ml.",
        price: 0.8,
        available: true,
      },
      {
        id: "bp-9",
        shopId: "burger-project",
        categoryId: "drinks",
        name: "Χειροποίητη Λεμονάδα",
        description: "Φρέσκο λεμόνι, δυόσμος, χωρίς ζάχαρη.",
        price: 2.9,
        available: true,
      },
    ],
  },

  /* ------------------------- Καφεκοπτείο Ελλάς --------------------------- */
  "kafekopteio-ellas": {
    shopId: "kafekopteio-ellas",
    categories: [
      { id: "coffee", label: "Καφέδες", emoji: "☕", sortOrder: 1 },
      { id: "cold", label: "Κρύα Ροφήματα", emoji: "🧊", sortOrder: 2 },
      { id: "snacks", label: "Σνακ", emoji: "🥐", sortOrder: 3 },
    ],
    items: [
      {
        id: "ke-1",
        shopId: "kafekopteio-ellas",
        categoryId: "coffee",
        name: "Espresso Διπλός",
        description: "Μείγμα 100% arabica, φρεσκοκαβουρδισμένο στο κατάστημα.",
        price: 2.2,
        popular: true,
        available: true,
      },
      {
        id: "ke-2",
        shopId: "kafekopteio-ellas",
        categoryId: "coffee",
        name: "Cappuccino",
        description: "Βελούδινος αφρός γάλακτος, επιλογή κανέλας.",
        price: 2.8,
        available: true,
      },
      {
        id: "ke-3",
        shopId: "kafekopteio-ellas",
        categoryId: "coffee",
        name: "Ελληνικός Διπλός",
        description: "Παραδοσιακός, σε χόβολη.",
        price: 2,
        available: true,
      },
      {
        id: "ke-4",
        shopId: "kafekopteio-ellas",
        categoryId: "cold",
        name: "Freddo Espresso",
        description: "Διπλός espresso, χτυπημένος με πάγο.",
        price: 3,
        popular: true,
        available: true,
      },
      {
        id: "ke-5",
        shopId: "kafekopteio-ellas",
        categoryId: "cold",
        name: "Freddo Cappuccino",
        description: "Με αφρόγαλα και επιλογή γλυκύτητας.",
        price: 3.3,
        available: true,
      },
      {
        id: "ke-6",
        shopId: "kafekopteio-ellas",
        categoryId: "snacks",
        name: "Κρουασάν Βουτύρου",
        description: "Ζύμη σφολιάτας, ψημένο κάθε πρωί.",
        price: 2.4,
        available: true,
      },
      {
        id: "ke-7",
        shopId: "kafekopteio-ellas",
        categoryId: "snacks",
        name: "Τυρόπιτα Χωριάτικη",
        description: "Χειροποίητο φύλλο, φέτα Δωδεκανήσου.",
        price: 2.9,
        available: true,
      },
    ],
  },

  /* ---------------------- Ζαχαροπλαστείο Μελίνα -------------------------- */
  "zacharoplasteio-melina": {
    shopId: "zacharoplasteio-melina",
    categories: [
      { id: "sweets", label: "Γλυκά Ταψιού", emoji: "🍯", sortOrder: 1 },
      { id: "cakes", label: "Τούρτες", emoji: "🎂", sortOrder: 2 },
      { id: "pastry", label: "Παγωτά & Άλλα", emoji: "🍨", sortOrder: 3 },
    ],
    items: [
      {
        id: "zm-1",
        shopId: "zacharoplasteio-melina",
        categoryId: "sweets",
        name: "Γαλακτομπούρεκο",
        description: "Κρέμα σιμιγδαλιού, τραγανό φύλλο, σιρόπι λεμονιού.",
        price: 3.6,
        popular: true,
        available: true,
      },
      {
        id: "zm-2",
        shopId: "zacharoplasteio-melina",
        categoryId: "sweets",
        name: "Μπακλαβάς",
        description: "Καρύδι, κανέλα, μέλι ελάτης.",
        price: 3.4,
        available: true,
      },
      {
        id: "zm-3",
        shopId: "zacharoplasteio-melina",
        categoryId: "sweets",
        name: "Ρεβανί",
        description: "Αφράτο σιροπιαστό με άρωμα πορτοκαλιού.",
        price: 3.1,
        available: true,
      },
      {
        id: "zm-4",
        shopId: "zacharoplasteio-melina",
        categoryId: "cakes",
        name: "Τούρτα Σοκολάτα 1kg",
        description: "Τρεις στρώσεις παντεσπάνι, γκανάς σοκολάτας.",
        price: 22,
        popular: true,
        available: true,
      },
      {
        id: "zm-5",
        shopId: "zacharoplasteio-melina",
        categoryId: "cakes",
        name: "Cheesecake Φράουλα (κομμάτι)",
        description: "Βάση μπισκότου, τυρί κρέμα, σάλτσα φράουλας.",
        price: 4.5,
        available: true,
      },
      {
        id: "zm-6",
        shopId: "zacharoplasteio-melina",
        categoryId: "pastry",
        name: "Παγωτό Οικογενειακό 1L",
        description: "Βανίλια, σοκολάτα ή κανέλα-καραμέλα.",
        price: 8.9,
        available: true,
      },
    ],
  },

  /* --------------------- Ταβέρνα το Στέκι της Πλατείας ------------------- */
  "steki-tis-plateias": {
    shopId: "steki-tis-plateias",
    categories: [
      { id: "mageirefta", label: "Μαγειρευτά", emoji: "🍲", sortOrder: 1 },
      { id: "grill", label: "Της Ώρας", emoji: "🔥", sortOrder: 2 },
      { id: "salads", label: "Σαλάτες", emoji: "🥗", sortOrder: 3 },
      { id: "drinks", label: "Ποτά", emoji: "🍷", sortOrder: 4 },
    ],
    items: [
      {
        id: "sp-1",
        shopId: "steki-tis-plateias",
        categoryId: "mageirefta",
        name: "Μουσακάς",
        description: "Πατάτα, μελιτζάνα, κιμάς και σπιτική μπεσαμέλ.",
        price: 9.5,
        popular: true,
        available: true,
      },
      {
        id: "sp-2",
        shopId: "steki-tis-plateias",
        categoryId: "mageirefta",
        name: "Γεμιστά με Ρύζι",
        description: "Ντομάτες και πιπεριές, με φέτα και πατάτες φούρνου.",
        price: 8.6,
        available: true,
      },
      {
        id: "sp-3",
        shopId: "steki-tis-plateias",
        categoryId: "mageirefta",
        name: "Κοκκινιστό Μοσχάρι",
        description: "Σιγομαγειρεμένο με μακαρόνια και τριμμένο κεφαλοτύρι.",
        price: 11.4,
        available: true,
      },
      {
        id: "sp-4",
        shopId: "steki-tis-plateias",
        categoryId: "grill",
        name: "Μπιφτέκι Γεμιστό",
        description: "Με φέτα και πιπεριά, συνοδεία πατάτες τηγανητές.",
        price: 9.9,
        available: true,
      },
      {
        id: "sp-5",
        shopId: "steki-tis-plateias",
        categoryId: "salads",
        name: "Χωριάτικη Σαλάτα",
        description: "Ντομάτα, αγγούρι, φέτα ΠΟΠ, ελιές Καλαμών, κάπαρη.",
        price: 6.8,
        popular: true,
        available: true,
      },
      {
        id: "sp-6",
        shopId: "steki-tis-plateias",
        categoryId: "drinks",
        name: "Κρασί Χύμα 500ml",
        description: "Λευκό ή κόκκινο, τοπικής παραγωγής.",
        price: 4.5,
        available: true,
      },
    ],
  },
};
